source ~/.config/nvim/modules/general.vim
source ~/.config/nvim/modules/plugins.vim
source ~/.config/nvim/modules/font.vim
source ~/.config/nvim/modules/cursor.vim
source ~/.config/nvim/modules/preferences.vim
source ~/.config/nvim/modules/gui.vim
source ~/.config/nvim/modules/f-keys.vim
source ~/.config/nvim/modules/workspaces.vim
source ~/.config/nvim/modules/leader.vim
